apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: php-job-demo
  labels:
    app: php-job-demo
    component: web
spec:
  type: LoadBalancer
  selector:
    app: php-job-demo
    component: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
