# ServiceAccount + RBAC for the scaling monitor to query Kubernetes API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaling-monitor
  namespace: php-job-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scaling-monitor-role
  namespace: php-job-demo
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["list"]
  - apiGroups: ["keda.sh"]
    resources: ["scaledobjects", "scaledjobs"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaling-monitor-binding
  namespace: php-job-demo
subjects:
  - kind: ServiceAccount
    name: scaling-monitor
    namespace: php-job-demo
roleRef:
  kind: Role
  name: scaling-monitor-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scaling-monitor-script
  namespace: php-job-demo
data:
  monitor.sh: |
    #!/bin/sh
    set -e

    # Determine scaling mode by checking which KEDA resources exist
    SCALING_MODE="unknown"
    if kubectl get scaledobject worker-scaled-object -n php-job-demo >/dev/null 2>&1; then
      SCALING_MODE="scaledobject"
    fi
    if kubectl get scaledjob worker-scaled-job -n php-job-demo >/dev/null 2>&1; then
      SCALING_MODE="scaledjob"
    fi

    # Count queue depth from PostgreSQL
    QUEUE_DEPTH=$(PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -t -A -c \
      "SELECT COUNT(*) FROM messenger_messages WHERE delivered_at IS NULL AND available_at <= NOW()" 2>/dev/null || echo "0")

    # Count pods by state
    ACTIVE_PODS=$(kubectl get pods -n php-job-demo -l component=worker --field-selector=status.phase=Running --no-headers 2>/dev/null | wc -l || echo "0")
    PENDING_PODS=$(kubectl get pods -n php-job-demo -l component=worker --field-selector=status.phase=Pending --no-headers 2>/dev/null | wc -l || echo "0")

    # Count ScaledJob completed/failed Jobs (only relevant in scaledjob mode)
    COMPLETED_JOBS=0
    FAILED_JOBS=0
    if [ "$SCALING_MODE" = "scaledjob" ]; then
      COMPLETED_JOBS=$(kubectl get pods -n php-job-demo -l component=worker-job --field-selector=status.phase=Succeeded --no-headers 2>/dev/null | wc -l || echo "0")
      FAILED_JOBS=$(kubectl get pods -n php-job-demo -l component=worker-job --field-selector=status.phase=Failed --no-headers 2>/dev/null | wc -l || echo "0")
      # Also count active pods from ScaledJob
      ACTIVE_PODS=$(kubectl get pods -n php-job-demo -l component=worker-job --field-selector=status.phase=Running --no-headers 2>/dev/null | wc -l || echo "0")
      PENDING_PODS=$(kubectl get pods -n php-job-demo -l component=worker-job --field-selector=status.phase=Pending --no-headers 2>/dev/null | wc -l || echo "0")
    fi

    # Insert metrics into PostgreSQL
    PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c \
      "CREATE TABLE IF NOT EXISTS scaling_metrics (
        id SERIAL PRIMARY KEY,
        recorded_at TIMESTAMP DEFAULT NOW(),
        queue_depth INTEGER,
        active_pods INTEGER,
        pending_pods INTEGER,
        completed_jobs INTEGER,
        failed_jobs INTEGER,
        scaling_mode VARCHAR(20),
        notes TEXT
      );" 2>/dev/null

    PGPASSWORD="$DB_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c \
      "INSERT INTO scaling_metrics (queue_depth, active_pods, pending_pods, completed_jobs, failed_jobs, scaling_mode)
       VALUES ($QUEUE_DEPTH, $ACTIVE_PODS, $PENDING_PODS, $COMPLETED_JOBS, $FAILED_JOBS, '$SCALING_MODE');"

    echo "[$(date)] Recorded: queue=$QUEUE_DEPTH active=$ACTIVE_PODS pending=$PENDING_PODS completed=$COMPLETED_JOBS failed=$FAILED_JOBS mode=$SCALING_MODE
---
# CronJob that runs every minute to record scaling metrics
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scaling-monitor
  namespace: php-job-demo
  labels:
    app: php-job-demo
    component: monitor
spec:
  schedule: "* * * * *"   # Every minute
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 50
      template:
        spec:
          serviceAccountName: scaling-monitor
          containers:
            - name: monitor
              image: bitnami/kubectl:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  # Install psql client
                  apt-get update -qq && apt-get install -y -qq postgresql-client >/dev/null 2>&1 || true
                  sh /scripts/monitor.sh
              env:
                - name: DB_HOST
                  value: "<REPLACE_ME>"    # e.g., a434815-akamai-prod-3365827-default.g2a.akamaidb.net
                - name: DB_PORT
                  value: "<REPLACE_ME>"    # e.g., 28213
                - name: DB_USER
                  value: "<REPLACE_ME>"    # e.g., app
                - name: DB_PASSWORD
                  value: "<REPLACE_ME>"    # e.g., app_password
                - name: DB_NAME
                  value: "<REPLACE_ME>"    # e.g., job_queue_demo
              volumeMounts:
                - name: scripts
                  mountPath: /scripts
          volumes:
            - name: scripts
              configMap:
                name: scaling-monitor-script
                defaultMode: 0755
          restartPolicy: Never
